# Generated by Django 3.2 on 2021-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0002_alter_redditsubreddit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachetoptickersliteralposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CacheTopTickersLiteralPosts',
                'managed': False,
            },
        ),
    ]
