# Generated by Django 3.1.7 on 2021-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nasdaqtickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('exchange', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nasdaqtickers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nysetickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('exchange', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nysetickers',
                'managed': False,
            },
        ),
    ]
