# Generated by Django 3.1.7 on 2021-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redditcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentusername', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('commenttext', models.CharField(blank=True, max_length=3000, null=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'redditcomment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redditpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField()),
                ('percentupvotes', models.IntegerField()),
                ('commentquanity', models.IntegerField()),
                ('posttext', models.CharField(blank=True, max_length=3000, null=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'redditpost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redditsubreddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subreddit', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'redditsubreddit',
                'managed': False,
            },
        ),
    ]
